### ISSUE TITLE
Python3 process killed - out of memory?

### ISSUE THREAD

**Issue by lxs602** [voidism/pywordseg#4]
Hi,

I hope English is ok.

Pywordseg fails when trying to cut a long string. See below.

I suppose it has run out of memory.

Can pywordseg be changed to run iteratively, to handle big input strings?
e.g. 
https://stackoverflow.com/questions/19189522/what-does-killed-mean-when-a-processing-of-a-huge-csv-with-python-which-sudde?answertab=votes#tab-top

謝謝,

路加

> Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
> [GCC 9.3.0] on linux
>from pywordseg import *
>seg = Wordseg(batch_size=64, embedding='elmo', elmo_use_cuda=False, mode="CN")
>[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
>seg.cut(["她半年后就要出国了。", "很少人这么认为。", "这周我一直在工作。", "明天下午之前我会把它完成。", "自己动手真好。", "那个发现纯属偶然。", "在英国的时候，我经常看参考书。", "我弟弟会经常彻夜不睡。", "你不得不制造一些借口。", "她可能出什么事了。", "你参加社团活动吗？", "我找到那把我一直在找的钥匙了。", "我丢了我的伞。", "她是他的一切。", "接电话。", "我在报纸上看到了它。", "请把它充入我的账户。", "雨不停，我们不会出去。", "这和我那本是同一本书。", "他们是热爱和平的人。", "我觉得你说的是真的。", "可以原谅我吗？", "我们没机会赢那些一流选手。", "他发誓要戒烟。", "在明天前完成报告几乎是不可能的。", "他昨天看了一部最有趣的小说。", "如果可能的话，我想环游世界。", "我是网球俱乐部的会员。", "医生，请给这孩子急救。", "据说山上的天气变化很快。", "他后悔在校时没用功读书。", "我可以用支票付吗？", "如果他年轻一点，他将很适合这个职位。", "他给我的工作作出了明确指示。", "他向权力屈服。", "是在昨天Jake打破了这扇窗。", "今天糟糕透了，所以我准备去喝一杯就直接上床。", "如果没有你，这个世界很孤单。", "啊，我认识这个男人！", "待在那儿别动。", "沿着这条路直走，到第三个红绿灯的地方右转。", "他正坐在会议室里。", "等她回来的时候问问她。", "他说得很大声。", "差不多两周John的病才好了。", "我们必须设法打破这个僵局。", "十年后，我们的城市将改变许多。", "你咖啡喝得太多了。", "我有好几打呢。", "我无法想象另一个星球上的生物。", "温度计往往低于零度。", "要完成实验，三个月太短了。", "“这些车是你的吗？”“是的，是我的。”", "我叔叔住在学校附近。", "去踢足球吧。", "合同已经到手了，那就出去庆祝一下吧。", "我难以用言语表达我的感情。", "我无法治愈心碎。", "猫抓住了老鼠。", "直到那时，他才意识到他已经上当受骗。", "他的医生建议他戒烟。", "我爸爸很忙。", "他用了一些手段来和Nancy私下交谈。", "把这些座位留给老人。", "我无法取代她做英语老师。", "他们粗心大意，还没意识到危险。", "她挥着她的手，直到火车消失在视线之外。", "当她发现他们还没有学校，她就办了一个。", "谢谢你的答复。", "Jack买不起新自行车。", "他寻找一切可能的逃生途径。", "对严格限制经济的批评蜂拥而来。", "这药创造了奇迹。", "你最好打消这么可笑的念头。", "我看见一个长头发的女生。", "外交谈判帮助结束了冲突。", "我发现了我爸爸收藏了30年的报纸。", "如何克服日元升高是个大问题。", "你想走的时候就走吧。", "他们在画展上授予了她一等奖。", "你可以骑上我的摩托车去遛一圈。", "他给我们讲了一个有趣的故事，我们都笑了起来。", "如何料理黑鲷：做刺身是最好吃的。", "让我们来澄清一下这个问题。", "别忘了在你的信上贴张邮票。", "我的生意终于走上了正轨。", "如果你需要笔的话，我借你一支。", "我要回房间了，在那儿我可以学习。", "照这样的情况，很抱歉，我不能接受你的盛情邀请。", "在一天之内完成它几乎是不可能的。", "接下来该采取什么行动就交给你了。", "老师给我们布置了家庭作业。", "我们看着这孩子玩耍。", "你开始学习英语了吗？", "它们是瓜。", "你走了，我们都会想你的。", "电视的优点在于它给体育爱好者提供了更大的方便。", "我没有拜访他，因为我感冒了。", "乘公交车费时。", "由于火车延误，我迟到了。", "他还没来。他肯定错过公交车了。", "这种款式的帽子现在很流行。", "其他的一切都好。", "你可以想象在月球上行走吗？", "你会溜冰吗？", "他有可能赢得比赛。", "这件事至关重要。", "不要拉我的腿！", "我无法相信自己的眼睛。", "我去听他的演讲去晚了。", "你考虑周到，没有打扰我们。", "这件事他铭记于心。", "这本书对你来说读起来太难了。", "我什么都不想喝。", "一块岩石从上面落下。", "我头痛。", "布什继里根之后当上了总统。", "他的努力没有成果。", "今天刮冷风。", "你在撒谎。", "自助者天助。", "和你的车比起来，我的车很小。", "他很年轻，更重要的是，他很帅。", "和她争辩是没用的。", "太可惜了！", "听到她成功的消息，他很高兴。", "男孩们窃窃私语，我知道他们准备做些什么。", "我要预订一间6月3日的单人房。", "请帮我找一下我的钱包。", "她给我讲了一个有趣的故事。", "他登上了前往洛杉矶的飞机。", "什么时候开始？", "他儿子小时候就死于癌症了。", "这本书有精美的插图。", "她和她妹妹一样亲切。", "随着时间的推移，比赛增加了规则以使之更安全。", "他看上去是一个十足的绅士。", "金子比水重得多。", "我们的任务到目前为止很轻松，但从现在开始将会变得很难。", "你自己拿蛋糕吃吧。", "他给我讲述了他的一生。", "事故耽误了我们半小时。", "这种秘密总有一天会被揭露的。", "我没什么可依靠的了。", "我做完我的功课后，就读这本书。", "能不能麻烦你告诉我去邻村怎么走？", "她住在罗素广场56号。", "我们有很多听众。", "请写信告诉我你们学校的情况。", "看见新鲜龙虾，我有了食欲。", "最后三周，Jim一直试图带我出去吃饭。", "这狗跑得多快啊！", "你上班迟到了。", "护士会告诉你怎么做。", "不要相信一个你一点都不了解他过去的人。", "下周我去温哥华看我妹妹。", "罗杰斯先生和史密斯小姐昨天宣布订婚。", "你多久后需要它？", "诚信是一种重要的美德。", "鲍勃第一个到达终点线。", "这是我见过最美的景色了。", "科学和数学我都喜欢。", "我们的计划从一开始就出错了。", "她不喜欢我说话的方式。", "你不这么认为吗？", "Tom否认偷了钱。", "我想减肥。", "我听到这个消息很吃惊。", "她一直和她的兄弟争吵。", "只有为数不多的几个电视节目值得关注。", "我不明白为什么你这么批评他。", "你想再来杯酒吗？", "他努力工作。", "自由是有代价的。", "几分钟后，电话响了。", "月球是地球唯一的卫星。", "他和他的姐妹们目前都住在东京。", "孩子们洗了他们的脚。", "我的计划是参观苏格兰的古堡。", "他是哈佛大学的生物学教授。", "他长大了会成为一名医生。", "银行对风险客户收取较高的贷款利息。", "你为什么说要去公园散步？", "观众人数庞大。", "写下你名字的大写字母。", "我不太明白他说什么。", "我对外籍员工没有偏见。", "我明早八点来接你。", "我相信他会信守诺言。", "我们看见池里有很多活鱼。", "用鼻子顶住一个球很困难。", "您学习吗？", "他有很多历史书籍。", "所有迹象表明她好起来了。", "即使他们有很好的酒单，我也不想在这里用餐。", "建筑物在地震中摇晃。", "由医生来决定某人何时该死是对的吗？", "谁来为风险投资提供资金？", "他很快便与小区里新来的男孩交上了朋友。", "他的政权必定会崩溃。", "小偷迅速地窜入了人群。", "我上周不忙。", "游泳使腿部强健。", "现在的人教育程度比以前高得多。", "我不能让自己做这样的事。", "接受对方的准则就是给予他权力。", "我将确保你们在第一年后有一个增长。", "他对日本的历史非常感兴趣。我们很惊讶他在这方面的丰富知识。", "把你的自行车放好。", "昨天是Alice去了演唱会。", "我们去了林中散步。", "汽笛声响起，船开始慢慢地驶离港口。", "孩子们应该每天喝牛奶。", "这张照片让我想起童年的快乐时光。", "简而言之，我不同意。", "但是他不常微笑。", "要去博物馆，你就得乘那辆车。", "除非雨停了，我们才会出去。", "我爸爸对我的爱和照顾不比我妈妈少。", "他试图游过河，但是失败了。", "告诉我你对湘南做了什么。", "我已经受够了这个计划。", "我发现他在花园里干活。", "毕加索是个有名的艺术家。", "这是一个例外。", "生活很困难，但我更坚强。", "这个班有多少男生？", "这一消息证实了我的怀疑。", "看那座被雪覆盖的山。", "她没有任何亲戚朋友照顾她。", "现在的孩子认为解决任何生活问题都像重新开始一个电脑游戏那么简单。", "我们也去了庙里。", "我想要去伦敦。", "他大半生都住在国外。", "情况一天比一天差。", "这架飞机一次可以携带40名乘客。", "你们对外语感兴趣吗？", "没有人跑在他前面。", "如果我现在有100万日元，我会买辆车。", "你相信上帝吗？", "在某种程度上你是对的，但我还是有疑问。", "我们终于登上了富士山山顶。", "他们午饭吃了三明治。", "我也想要和你身上那件同样的外套。", "你觉得她最想要什么纪念品？", "他们生活得很幸福。", "她有很多事要做。", "我直视他的眼睛。", "全体销售人员通宵达旦地工作了一周。", "这个诗人兼学者死了。", "他简单地阐述了他的理由。", "有效期到1997年3月31日为止。", "我们去滑雪怎么样？", "我们采取了强有力的预防措施。", "他在森林中迷了路。", "不要把我们的计划告诉任何人。", "Tom躲在桌子底下。", "他告诉了我们许多经验教训。", "这房子里似乎在办派对。", "我会教你怎么开车。", "威尼斯的圣马可广场在夏季总是挤满了游客。", "我们必须保持家庭传统。", "他能游得很快。", "一个神圣的仪式在庄严的庙宇中举行。", "我厌倦了我的工作。", "你们周日送货吗？", "我想再来一杯啤酒。", "他可能迷路了。", "他出卖了我。", "天冷得足以让湖结冰。", "我不知道，也不想知道。", "去年她离开了日本。", "今晚我将在朋友家过夜。", "我需要购买新的镜架。", "我弟弟手里拿着一个摄像机。", "我们在这里下车吧。", "Kate, 坐吧。", "我妹妹21岁，是个大学生。", "你会发现难以满足她。", "除非我死了！", "我尊敬长辈。", "有什么比失明更不幸的呢？", "他们的合同在这个月底到期。", "帮我一下。", "爱都是嫉妒的。", "仅三分之一的成员出席了会议。", "让我看看那些照片。", "厕所冲水不正常。", "我们的孩子喜欢狗，但我更喜欢猫。", "我欠她10美元。", "我们必须考虑到他很年轻。", "她一到，我们就开始。", "我挑不出他的毛病。", "你能为我腾出几分钟时间吗?", "2月我们有个短期休假。", "你有义务还债。", "她没有辜负我们的期望。", "停车场是免费的。", "他父母对他期望过高。", "问题是我们如何应付目前的困难。", "她戴上了她的帽子。", "我想看看。", "你在听我说吗？", "孩子在这条河里游泳太危险了。", "报纸、杂志和新闻广播讲述着世界上正在发生的事。", "每年有成千上万的外国人访问日本。", "这被认为是一件大事。", "如果你快一点，还能赶上他。", "老人试图游5公里。", "除了雨天，我都是骑车去上班的。", "她原谅了男孩的粗鲁。", "病人随时会死。", "是它的两倍大。", "一个人要为他的行为负责。", "你会代替我去派对吗？", "她放下手中的针线活，并站了起来。", "这是找零。", "他是日本最伟大的艺术家之一。", "父亲常常在空闲时间读侦探小说。", "我通常在晚上洗澡。", "这对他没有影响。", "他每天去学校学习。", "妈妈为我准备了午饭。", "你能再给我点茶吗？", "一些人通过阅读来放松。", "整个夏天，我们在那里过得很愉快。", "有了坚定的目标，你会做得很好。", "我厌倦了他的老笑话。", "她的眼里涌出了泪水。", "公园里有很多人。", "第一排的座位5美元。", "你更喜欢哪个，这个还是那个？", "这是去牛津大学的车吗？", "我们将于下周日结婚。", "你觉得这件毛衣怎么样？", "小丑做了个鬼脸。", "她下周日回家，也就是10号。", "我们的生活不是由物质，而是由精神来下定义的。", "我们有你的尺寸，但是没有那个颜色。", "我赚钱养家。", "在这儿等到他回来为止。", "你不应该在学校大楼里奔跑。", "我们国家不缺石油。", "他被选为市长。", "这男人和他妻子互相帮助。", "爸爸今天很不耐烦。", "那个学生跑得很快，不是吗？", "你是我的阳光。", "这音乐值得听许多次。", "许多人在工业城市工作。", "严重吗？", "物价上涨了。", "那栋灰色的大楼吗？", "这首歌让我想家了。", "你该戒烟戒酒了。", "爸爸乘早上7点的地铁去上班。", "我认识史密斯先生有好多年了。", "我不会说法语，也不会说德语。", "我们按例处罚了他。", "老实说，我不喜欢他。", "要掌握法语一点都不容易。", "我的房间号是多少？", "过河拆桥。", "油墨快没了。", "老人坐了下来。", "他出国留学了。", "我用两千日元买了这本书。", "这部电影为她赢得了人气。", "她给客人看了她的宝宝。", "他很快就会回来的。", "这只是偶发事件。", "他进来的同时，铃响了。", "据说他爸爸在外国去世了。", "消防车到达之前，房子就全烧了。", "我没见过也没听过这样的事。", "你支持还是反对堕胎？", "Ken七月底要去美国了。", "你的学校在这个城市吗？", "最后她没有来。", "你叔叔让你开他的车了吗？", "昨晚我领居家着火了。", "你的提议值得考虑。", "她现在正待在她叔叔家。", "你对女人有一套。", "我身负一个重要的任务。", "着火了！快跑啊！", "好习惯是从小养成的。", "我们偶然碰到了她。", "祝你旅途愉快。", "我开门的时候弄坏了锁。", "我有两个儿子，一个在东京，另一个在名古屋。", "她是什么时候出生的？", "你现在好点了吗？", "我胃痛。", "一些同学看见我给了他巧克力。", "国际货币基金组织不考虑再借款给该国。", "因为我想成为翻译。", "乡间有很多树。", "道路结冰导致了很多起事故。", "迟做总比不做好。", "你乘飞机还是乘火车去？", "我洗完碗后看了电视。", "这里允许拍照吗？", "他是非不分。", "数据表明年轻人抽烟的现象没有减少。", "奈良是个非常古老的城市。", "她迷路了，紧接着天开始下雨了。", "她认为计划很好，但不可行。", "我们为表演者鼓掌。", "我在找关于古罗马历史的书。", "我没朋友帮我。", "我不想等那么久。", "他的忠告总是很明智。", "我们都期待看到你和你的家人。", "这是这个诗人出生的村子。", "让窗子关着。", "他的故事一部分是真的。", "他是美国人。", "史密斯夫妇现在分居了。", "我们吃面包夹黄油。", "她不会乘飞机因为害怕坠机。", "你成功与否取决于你自身的努力。", "他受邀做俱乐部的主席。", "知足常乐。", "今晚你可以在他家联络到他。", "你工作太努力了。", "得不到的东西就最想得到。", "学校8点半开始上课。", "这个月底前，我们必须交报告。", "他这个时候该到了。", "我很感激你在我生病的时候照顾我。", "很难说明天的天气将会怎样。", "他丢了块肉给一条狗。", "我会给你开个药方。", "不要探听别人的事。", "纽约市的人口有多少？", "天知道他去哪儿了。", "她在一棵树下坐着。", "我的一个叔叔给我了一些有用的建议。", "她很想要一条新的连衣裙。", "日本人放弃了战争。", "控制一个班级需要你做老师的所有技能。", "我想知道这个冬天在我们的城市会不会下雪。", "他弟弟是个有名的足球选手。", "铃响了。", "响了。", "她的悲伤无法言喻。", "我肯定你会喜欢我们今晚的菜肴。", "我能问一些问题吗？", "我期待很快就能收到你的信。", "他在澳大利亚长大。", "我弟弟没我两年前高。", "他一直很担心他的女儿。", "难怪她表示不想再见到他了。因为他们分手了。", "他的化学很差。", "教堂位于山脚。", "在公车上，一个陌生人和我说了话。", "我很钦佩他的才干。", "我猜想你可能是对的。", "老师不可能说过这样的事。", "失之毫厘，谬之千里。", "今天我头痛欲裂。", "退休后他的收入少了一半。", "她答应几时见他？", "我对你的厚颜无耻感到惊讶。", "她太放任她的孩子们了。", "年轻人应该尊敬老人。", "他不打算买一个摄像机。", "他在城市里一直受到噪音或者其他的干扰。", "他们的旅行因为火车延期了。", "Steve看上去很高兴。", "她去过巴黎。", "我看见书桌上有朵花。", "我头撞到了门，肿了一块。", "你必须马上开始。", "我们在下个加油站停一下。", "你做了什么？", "舞台上有著名音乐家吗？", "请你把冷气调高点。", "这不是我喜欢的类型。", "我觉得你的工作可以。", "我还有其他选择吗？", "这孩子能数到20。", "这场秀棒极了，但是门票太贵了。", "火车因大雪被耽搁了。", "这只梨闻上去很香。", "“你想再来点咖啡吗？”“不，谢谢。我够了。”", "请把你们的全盘计划告诉我。", "“我爸爸不喝酒。”“我爸爸也不喝。”", "上个月，我们20岁的女儿生了个女孩。", "他们坚持让他走。", "我一直忙于写一部短篇小说。", "我的工作是洗碗。", "我想坐在无烟区。", "这辆车保养起来很贵。", "物极必反。", "如果我是你，我会在这种困难的情况下做同样的事。", "让我试试。", "他不惜用私人时间来工作。", "会议在9点结束了。"])
>**Killed**

**Comment by voidism** [comment]
Hi @lxs602

My code has already supported running iteratively based on the batch size you specified.
If you only have a limited RAM, you can reduce the batch_size from "64" to a lower value like "2" or "4". This should solve your problem.

btw, when I use my Macbook with only 8G RAM to cut your examples with pywordseg (batch_size=64), it works fine. Do you have only a very small RAM on your machine?

**Comment by lxs602** [comment]
Hi,

Sorry, I don't mean to question your coding, I know not a lot about code. 

I did try changing the batch size to 4, and then 2, and then 1, but it still ran out of memory.

My laptop has 8GB RAM, and the RAM use at rest is about 400Mb.  

The swap partition is only 1GB. I had forgotten I made it so small, which was to protect my SDD hard drive.

I made a 10GB swapfile on an external hard drive via USB 3.0 and it does now run, though doing this is very slow.  

Nonetheless, I look forward to trying ELMo on one of  the files I need to segment (about 35,000 sentences) with a lot of phonetic loan words (non-Chinese place names and people) and some rare vocabulary. 

謝謝,

L

**Comment by lxs602** [comment]
Hi, I hadn't read your paper before I made the comment above.  If you don't mind me asking, do you have any suggestions for files with a high proportion of phonetic loan words, of non-Chinese origin (e.g. 路加  = 'Luke')?

謝謝

**Comment by voidism** [comment]
Hi,

I think phonetic loan words are not very common in my training data, so the segmentation results may not be good.
I think Pywordseg usually segments phonetic loan words into smaller segments.

You can try to include an external dictionary to handle these special words manually.
See https://github.com/voidism/pywordseg#include-external-dictionary-optional

**Comment by lxs602** [comment]
Hi, thanks, I found a word list.  

Splitting the input file into lines of 100 also worked well for managing the memory problem.

Best wishes.

L

**Comment by lxs602** [comment]
See below. Thanks.
https://github.com/lxs602/Chinese-Mandarin-Dictionaries/blob/main/README.md#cuv-bible-concordance-with-world-english-bible-translation
